server {
    listen 443 ssl;
    server_name nginx-expired;

    ssl_certificate     /etc/nginx/certs/expired.crt;
    ssl_certificate_key /etc/nginx/certs/expired.key;

    location / {
        return 200 '{"status":"ok","service":"nginx-expired"}';
        add_header Content-Type application/json;
    }
}
