server {
    listen 443 ssl;
    server_name nginx-expiring;

    ssl_certificate     /etc/nginx/certs/expiring.crt;
    ssl_certificate_key /etc/nginx/certs/expiring.key;

    location / {
        return 200 '{"status":"ok","service":"nginx-expiring"}';
        add_header Content-Type application/json;
    }
}
