server {
    listen 443 ssl;
    server_name nginx-healthy;

    ssl_certificate     /etc/nginx/certs/valid.crt;
    ssl_certificate_key /etc/nginx/certs/valid.key;

    location / {
        return 200 '{"status":"ok","service":"nginx-healthy"}';
        add_header Content-Type application/json;
    }
}
