server {
    listen 443 ssl;
    server_name nginx-wronghost;

    ssl_certificate     /etc/nginx/certs/wronghost.crt;
    ssl_certificate_key /etc/nginx/certs/wronghost.key;

    location / {
        return 200 '{"status":"ok","service":"nginx-wronghost"}';
        add_header Content-Type application/json;
    }
}
